In [15]:
import numpy as np
from theano import function
import theano.tensor as T

In [14]:
someArray = np.asarray([[1,2], [3,4], [5,6]])
someArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
x = T.dmatrix('x')
y = T.dmatrix('y')
z = x + y
f = function([x, y], z)


In [25]:
a = T.vector()
b = T.vector()
out = a**2 + b**2 + 2*a*b
f = function([a,b], out)
f([1,2], [4,5])

array([ 25.,  49.])

In [30]:
x = T.dmatrix('x')
s = 1 / (1 + T.exp(-x))
logistic = function([x], s)
logistic([[0, 1], [-1, -2]])

array([[ 0.5       ,  0.73105858],
       [ 0.26894142,  0.11920292]])

In [31]:
s2 = (1 + T.tanh(x/2)) / 2
logistic2 = function([x], s2)
logistic2([[0, 1], [-1, -2]])

array([[ 0.5       ,  0.73105858],
       [ 0.26894142,  0.11920292]])

In [33]:
a, b = T.dmatrices('a', 'b')
diff = a - b
abs_diff = abs(diff)
diff_squared = diff ** 2
f = function([a, b], [diff, abs_diff, diff_squared])
f([[1,2], [3,4]], [[10,20], [30,40]])

[array([[ -9., -18.],
        [-27., -36.]]), array([[  9.,  18.],
        [ 27.,  36.]]), array([[   81.,   324.],
        [  729.,  1296.]])]